# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DO.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1329, 792)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-30, 0, 1371, 901))
        self.frame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.feedLabel = QtWidgets.QLabel(self.frame)
        self.feedLabel.setGeometry(QtCore.QRect(60, 80, 640, 341))
        self.feedLabel.setObjectName("feedLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(730, 80, 601, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 7, -1, 0)
        self.formLayout.setObjectName("formLayout")
        self.tPOLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tPOLabel.setFont(font)
        self.tPOLabel.setObjectName("tPOLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tPOLabel)
        self.tPOLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tPOLineEdit.setFont(font)
        self.tPOLineEdit.setObjectName("tPOLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tPOLineEdit)
        self.companyNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.companyNameLabel.setFont(font)
        self.companyNameLabel.setObjectName("companyNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.companyNameLabel)
        self.companyNameLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.companyNameLineEdit.setFont(font)
        self.companyNameLineEdit.setObjectName("companyNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.companyNameLineEdit)
        self.dO_dateLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dO_dateLabel.setFont(font)
        self.dO_dateLabel.setObjectName("dO_dateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dO_dateLabel)
        self.dO_dateLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dO_dateLineEdit.setFont(font)
        self.dO_dateLineEdit.setObjectName("dO_dateLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dO_dateLineEdit)
        self.dO_numberLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dO_numberLabel.setFont(font)
        self.dO_numberLabel.setObjectName("dO_numberLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dO_numberLabel)
        self.dO_numberLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dO_numberLineEdit.setFont(font)
        self.dO_numberLineEdit.setObjectName("dO_numberLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dO_numberLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, 10)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.poRetakeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.poRetakeButton.setFont(font)
        self.poRetakeButton.setObjectName("poRetakeButton")
        self.verticalLayout.addWidget(self.poRetakeButton)
        self.companyNameRetakeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.companyNameRetakeButton.setFont(font)
        self.companyNameRetakeButton.setObjectName("companyNameRetakeButton")
        self.verticalLayout.addWidget(self.companyNameRetakeButton)
        self.doDateRetakeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doDateRetakeButton.setFont(font)
        self.doDateRetakeButton.setObjectName("doDateRetakeButton")
        self.verticalLayout.addWidget(self.doDateRetakeButton)
        self.doNumberRetakeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doNumberRetakeButton.setFont(font)
        self.doNumberRetakeButton.setObjectName("doNumberRetakeButton")
        self.verticalLayout.addWidget(self.doNumberRetakeButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(1060, 730, 261, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.insertButton.setFont(font)
        self.insertButton.setObjectName("insertButton")
        self.horizontalLayout.addWidget(self.insertButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(730, 250, 601, 461))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.itemVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.itemVLayout.setContentsMargins(0, 0, 0, 0)
        self.itemVLayout.setObjectName("itemVLayout")
        self.itemDescriptionHLayout = QtWidgets.QHBoxLayout()
        self.itemDescriptionHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.itemDescriptionHLayout.setSpacing(6)
        self.itemDescriptionHLayout.setObjectName("itemDescriptionHLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(20, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setObjectName("textBrowser")
        self.itemDescriptionHLayout.addWidget(self.textBrowser)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(7, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.itemDescriptionHLayout.addWidget(self.textBrowser_3)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(7, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.itemDescriptionHLayout.addWidget(self.textBrowser_2)
        self.itemDescriptionHLayout.setStretch(0, 4)
        self.itemDescriptionHLayout.setStretch(1, 1)
        self.itemDescriptionHLayout.setStretch(2, 1)
        self.itemVLayout.addLayout(self.itemDescriptionHLayout)
        self.itemHorizontalLayout = QtWidgets.QHBoxLayout()
        self.itemHorizontalLayout.setObjectName("itemHorizontalLayout")
        self.itemComboVLayout = QtWidgets.QVBoxLayout()
        self.itemComboVLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.itemComboVLayout.setObjectName("itemComboVLayout")
        self.comboBox0 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox0.setFont(font)
        self.comboBox0.setObjectName("comboBox0")
        self.itemComboVLayout.addWidget(self.comboBox0)
        self.comboBox1 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox1.setFont(font)
        self.comboBox1.setObjectName("comboBox1")
        self.itemComboVLayout.addWidget(self.comboBox1)
        self.comboBox2 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.itemComboVLayout.addWidget(self.comboBox2)
        self.comboBox3 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox3.setFont(font)
        self.comboBox3.setObjectName("comboBox3")
        self.itemComboVLayout.addWidget(self.comboBox3)
        self.comboBox4 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox4.setFont(font)
        self.comboBox4.setObjectName("comboBox4")
        self.itemComboVLayout.addWidget(self.comboBox4)
        self.comboBox5 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox5.setFont(font)
        self.comboBox5.setObjectName("comboBox5")
        self.itemComboVLayout.addWidget(self.comboBox5)
        self.comboBox6 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox6.setFont(font)
        self.comboBox6.setObjectName("comboBox6")
        self.itemComboVLayout.addWidget(self.comboBox6)
        self.comboBox7 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox7.setFont(font)
        self.comboBox7.setObjectName("comboBox7")
        self.itemComboVLayout.addWidget(self.comboBox7)
        self.comboBox8 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox8.setFont(font)
        self.comboBox8.setObjectName("comboBox8")
        self.itemComboVLayout.addWidget(self.comboBox8)
        self.comboBox9 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox9.setFont(font)
        self.comboBox9.setObjectName("comboBox9")
        self.itemComboVLayout.addWidget(self.comboBox9)
        self.comboBox10 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox10.setFont(font)
        self.comboBox10.setObjectName("comboBox10")
        self.itemComboVLayout.addWidget(self.comboBox10)
        self.comboBox11 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox11.setFont(font)
        self.comboBox11.setObjectName("comboBox11")
        self.itemComboVLayout.addWidget(self.comboBox11)
        self.itemHorizontalLayout.addLayout(self.itemComboVLayout)
        self.receivedVLayout = QtWidgets.QVBoxLayout()
        self.receivedVLayout.setObjectName("receivedVLayout")
        self.orderedEdit0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit0.setFont(font)
        self.orderedEdit0.setObjectName("orderedEdit0")
        self.receivedVLayout.addWidget(self.orderedEdit0)
        self.orderedEdit1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit1.setFont(font)
        self.orderedEdit1.setObjectName("orderedEdit1")
        self.receivedVLayout.addWidget(self.orderedEdit1)
        self.orderedEdit3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit3.setFont(font)
        self.orderedEdit3.setObjectName("orderedEdit3")
        self.receivedVLayout.addWidget(self.orderedEdit3)
        self.orderedEdit2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit2.setFont(font)
        self.orderedEdit2.setObjectName("orderedEdit2")
        self.receivedVLayout.addWidget(self.orderedEdit2)
        self.orderedEdit4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit4.setFont(font)
        self.orderedEdit4.setObjectName("orderedEdit4")
        self.receivedVLayout.addWidget(self.orderedEdit4)
        self.orderedEdit5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit5.setFont(font)
        self.orderedEdit5.setObjectName("orderedEdit5")
        self.receivedVLayout.addWidget(self.orderedEdit5)
        self.orderedEdit6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit6.setFont(font)
        self.orderedEdit6.setObjectName("orderedEdit6")
        self.receivedVLayout.addWidget(self.orderedEdit6)
        self.orderedEdit7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit7.setFont(font)
        self.orderedEdit7.setObjectName("orderedEdit7")
        self.receivedVLayout.addWidget(self.orderedEdit7)
        self.orderedEdit8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit8.setFont(font)
        self.orderedEdit8.setObjectName("orderedEdit8")
        self.receivedVLayout.addWidget(self.orderedEdit8)
        self.orderedEdit9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit9.setFont(font)
        self.orderedEdit9.setObjectName("orderedEdit9")
        self.receivedVLayout.addWidget(self.orderedEdit9)
        self.orderedEdit10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit10.setFont(font)
        self.orderedEdit10.setObjectName("orderedEdit10")
        self.receivedVLayout.addWidget(self.orderedEdit10)
        self.orderedEdit11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.orderedEdit11.setFont(font)
        self.orderedEdit11.setObjectName("orderedEdit11")
        self.receivedVLayout.addWidget(self.orderedEdit11)
        self.itemHorizontalLayout.addLayout(self.receivedVLayout)
        self.orderedVLayout = QtWidgets.QVBoxLayout()
        self.orderedVLayout.setObjectName("orderedVLayout")
        self.receivedEdit0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit0.setFont(font)
        self.receivedEdit0.setObjectName("receivedEdit0")
        self.orderedVLayout.addWidget(self.receivedEdit0)
        self.receivedEdit1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit1.setFont(font)
        self.receivedEdit1.setObjectName("receivedEdit1")
        self.orderedVLayout.addWidget(self.receivedEdit1)
        self.receivedEdit2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit2.setFont(font)
        self.receivedEdit2.setObjectName("receivedEdit2")
        self.orderedVLayout.addWidget(self.receivedEdit2)
        self.receivedEdit3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit3.setFont(font)
        self.receivedEdit3.setObjectName("receivedEdit3")
        self.orderedVLayout.addWidget(self.receivedEdit3)
        self.receivedEdit4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit4.setFont(font)
        self.receivedEdit4.setObjectName("receivedEdit4")
        self.orderedVLayout.addWidget(self.receivedEdit4)
        self.receivedEdit5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit5.setFont(font)
        self.receivedEdit5.setObjectName("receivedEdit5")
        self.orderedVLayout.addWidget(self.receivedEdit5)
        self.receivedEdit6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit6.setFont(font)
        self.receivedEdit6.setObjectName("receivedEdit6")
        self.orderedVLayout.addWidget(self.receivedEdit6)
        self.receivedEdit7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit7.setFont(font)
        self.receivedEdit7.setObjectName("receivedEdit7")
        self.orderedVLayout.addWidget(self.receivedEdit7)
        self.receivedEdit8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit8.setFont(font)
        self.receivedEdit8.setObjectName("receivedEdit8")
        self.orderedVLayout.addWidget(self.receivedEdit8)
        self.receivedEdit9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit9.setFont(font)
        self.receivedEdit9.setObjectName("receivedEdit9")
        self.orderedVLayout.addWidget(self.receivedEdit9)
        self.receivedEdit10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit10.setFont(font)
        self.receivedEdit10.setObjectName("receivedEdit10")
        self.orderedVLayout.addWidget(self.receivedEdit10)
        self.receivedEdit11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.receivedEdit11.setFont(font)
        self.receivedEdit11.setObjectName("receivedEdit11")
        self.orderedVLayout.addWidget(self.receivedEdit11)
        self.itemHorizontalLayout.addLayout(self.orderedVLayout)
        self.itemHorizontalLayout.setStretch(0, 4)
        self.itemHorizontalLayout.setStretch(1, 1)
        self.itemHorizontalLayout.setStretch(2, 1)
        self.itemVLayout.addLayout(self.itemHorizontalLayout)
        self.itemVLayout.setStretch(0, 1)
        self.itemVLayout.setStretch(1, 100)
        self.infoTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.infoTextBrowser.setGeometry(QtCore.QRect(60, 470, 640, 291))
        self.infoTextBrowser.setObjectName("infoTextBrowser")
        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(60, 17, 171, 51))
        self.logoLabel.setStyleSheet("image: url(:/newPrefix/logo.PNG);")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/newPrefix/logo.PNG"))
        self.logoLabel.setScaledContents(False)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(620, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Pagul")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 450, 71, 17))
        self.label.setObjectName("label")
        self.feedLabel.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.logoLabel.raise_()
        self.titleLabel.raise_()
        self.label.raise_()
        self.infoTextBrowser.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.feedLabel.setText(_translate("Form", "TextLabel"))
        self.tPOLabel.setText(_translate("Form", "T-PO-"))
        self.companyNameLabel.setText(_translate("Form", "CompanyName"))
        self.dO_dateLabel.setText(_translate("Form", "DO_date"))
        self.dO_numberLabel.setText(_translate("Form", "DO_number"))
        self.poRetakeButton.setText(_translate("Form", "Retake"))
        self.companyNameRetakeButton.setText(_translate("Form", "Retake"))
        self.doDateRetakeButton.setText(_translate("Form", "Retake"))
        self.doNumberRetakeButton.setText(_translate("Form", "Retake"))
        self.insertButton.setText(_translate("Form", "insert"))
        self.nextButton.setText(_translate("Form", "next"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">item_part_number</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">ordered</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">received</span></p></body></html>"))
        self.infoTextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.titleLabel.setText(_translate("Form", "DO_OCR"))
        self.label.setText(_translate("Form", "INFO LOG"))
import logo_rc
